name: 매일 공고 수집

on:
  schedule:
    - cron: '20 5 * * *'  # UTC 00:00 = KST 09:00  
  workflow_dispatch:       # 수동 실행 버튼도 활성화

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests notion-client python-dotenv
      - run: python main.py
        env:
          BIZINFO_API_KEY: ${{ secrets.BIZINFO_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}